/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package src.co.usta.gui;

import com.sun.j3d.utils.applet.JMainFrame;
import src.co.usta.clases.Cubo;
import java.awt.Image;
import javax.swing.JFrame;

/**
 *
 * @author suare
 */
public class Figura extends javax.swing.JFrame {

    /**
     * Creates new form Figura
     */
    private boolean esferaCheck;
    private boolean cuboCheck;
    private boolean ejeX;
    private boolean ejeY;
    public Figura() {
        initComponents();
        esferaCheck = false;
        cuboCheck = false;
        ejeX = false;
        ejeY = false;
        check();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtLado = new javax.swing.JTextField();
        chkEsfera = new javax.swing.JCheckBox();
        chkCubo = new javax.swing.JCheckBox();
        txtRadio = new javax.swing.JTextField();
        lblRadio = new javax.swing.JLabel();
        lblLado = new javax.swing.JLabel();
        btnGenerar = new javax.swing.JButton();
        clr = new javax.swing.JColorChooser();
        txtVelocidadGiro = new javax.swing.JTextField();
        lblVelocidadGiro = new javax.swing.JLabel();
        txtTamañoTablero = new javax.swing.JTextField();
        lblTamañoTablero = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        chkEsfera.setText("Esfera");
        chkEsfera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkEsferaActionPerformed(evt);
            }
        });

        chkCubo.setText("Cubo");
        chkCubo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkCuboActionPerformed(evt);
            }
        });

        lblRadio.setText("Radio");

        lblLado.setText("Lado");

        btnGenerar.setText("Generar");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });

        txtVelocidadGiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVelocidadGiroActionPerformed(evt);
            }
        });

        lblVelocidadGiro.setText("Velocidad Giro");

        txtTamañoTablero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTamañoTableroActionPerformed(evt);
            }
        });

        lblTamañoTablero.setText("Tamaño tablero");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addComponent(btnGenerar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap(111, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblRadio)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(45, 45, 45)
                                    .addComponent(chkEsfera)
                                    .addGap(15, 15, 15)))
                            .addGap(87, 87, 87)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblLado)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtLado, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(26, 26, 26)
                                    .addComponent(chkCubo)
                                    .addGap(36, 36, 36)))
                            .addGap(69, 69, 69)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblTamañoTablero)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtTamañoTablero, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblVelocidadGiro)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtVelocidadGiro, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(clr, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chkEsfera)
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtRadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRadio)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblVelocidadGiro)
                            .addComponent(txtVelocidadGiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTamañoTablero)
                            .addComponent(txtTamañoTablero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chkCubo)
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLado))))
                .addGap(53, 53, 53)
                .addComponent(btnGenerar)
                .addGap(18, 18, 18)
                .addComponent(clr, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkEsferaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkEsferaActionPerformed
        if (esferaCheck == true) {
            esferaCheck = false;
        }
        else
        {
            esferaCheck = true;
            
        }
        check();
    }//GEN-LAST:event_chkEsferaActionPerformed

    private void chkCuboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkCuboActionPerformed
        if (cuboCheck == true) {
            cuboCheck = false;
        }
        else
        {
            cuboCheck = true;
        }
        check();
    }//GEN-LAST:event_chkCuboActionPerformed

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        //System.out.println(Double.parseDouble(txtLado.getText()));
        Image canvasAux;
        if(Integer.valueOf(txtLado.getText()) < Integer.valueOf(txtTamañoTablero.getText())){
            canvasAux = createImage(Integer.valueOf(txtTamañoTablero.getText()),Integer.valueOf(txtTamañoTablero.getText()));
            Cubo cubo = new Cubo(Integer.valueOf(txtVelocidadGiro.getText()));
            cubo.setColor(clr.getColor());
            cubo.setcImage(canvasAux);
            cubo.setMaxSize(Integer.valueOf(txtLado.getText()));
            JFrame fa = new JMainFrame(cubo, 0, 0);
            fa.setVisible(true);
        }else
        {
            System.err.println("no puede ser mayor el tamño del cubo que el de la pantalla");
        }
    }//GEN-LAST:event_btnGenerarActionPerformed

    private void txtVelocidadGiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVelocidadGiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVelocidadGiroActionPerformed

    private void txtTamañoTableroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTamañoTableroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTamañoTableroActionPerformed

    public void check() {
        if(esferaCheck == false && cuboCheck == false) {
            clr.setVisible(false);
            btnGenerar.enable(false);
            txtRadio.enable(false);
            txtLado.enable(false);
            chkCubo.enable(true);
            chkEsfera.enable(true);
            
            
        }      
        else {
            btnGenerar.enable(true);
            clr.setVisible(true);
            if(esferaCheck == true) {
                txtRadio.enable(true);
                chkCubo.enable(false);
            }
            if(cuboCheck == true) {
                txtLado.enable(true);
                chkEsfera.enable(false);
            }
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Figura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Figura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Figura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Figura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Figura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerar;
    private javax.swing.JCheckBox chkCubo;
    private javax.swing.JCheckBox chkEsfera;
    private javax.swing.JColorChooser clr;
    private javax.swing.JLabel lblLado;
    private javax.swing.JLabel lblRadio;
    private javax.swing.JLabel lblTamañoTablero;
    private javax.swing.JLabel lblVelocidadGiro;
    private javax.swing.JTextField txtLado;
    private javax.swing.JTextField txtRadio;
    private javax.swing.JTextField txtTamañoTablero;
    private javax.swing.JTextField txtVelocidadGiro;
    // End of variables declaration//GEN-END:variables
}
